apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tired-tortoise-go 
  janus-idp.io/tekton: tired-tortoise-go
  backstage.io/kubernetes-id: tired-tortoise-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: tired-tortoise-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  